sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PmhLt0Nn0TMsC9RYrcAXqRB5paVND3AbUPKd8biddwMPBQbNUBmngYHkhGWzNDt5LNVdX2GsJnEcLQrqGig9aheXPYx3SBWYLIQxVzyX2XWLYe9+9EEr06aWQNb449ndwKPiF6kaR5gsjiVypmyBjOHoDm8JfFTU9BIelDyR2qAgfWounfNWN6FhgSvJzM9zoXqJHSigFMvIBsbFZCjvR3cUcms0v80KfEyRMH4cR+xHa1yGi/Th/J49g4oLw/VToN9E2v4IwBDBDygBJLR7vp4kLfVVb18K+jDpi9xczJFHDNESltx3IHayi0NE6O7rEKdzIqu+nuaAB/xYPPtxxBmNahv4JEqgtO+CiX6Nn0e4gXYx8I9r2KT3mLTetHasJVdb5JDwyDPBx8S+vjfnxU4TzCQPt9ZICItUeheEQPLZPMcufpipfcXnzBMc9QgRdcE6eSua/b+p718FT7sqlZsFfXYvTRy7TROxDCgJa7e+5j+x+3SUZiy3zFbytqQUPTY0ZE9BSS5HU1JuNDzHU7nI9TfNJHJsmbSPXRmfYeApS+e/N9B3k7O0Y2VJgs8nqpYC7zdshRgC9iiyffaKQsQoA2RvhlLXRAU2HH5bNEewlesv7VlKChn2tD+AmhK+w+aEbTFUFKREVHkntiJfhkRx23b+SNlJuMRMKj8w9wY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/After-Dark_1626
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy